### ISSUE TITLE
Incorrect token URL 

### ISSUE THREAD

**Issue by brendandobbs** [SAP/xf-addons#10]
If we use a host name without a trailing '/' then the token URL is registered incorrectly. See the following from the Application CRD where there is a missing '/' in the tokenEndpointURL

```
credentials:
        csrfInfo:
          tokenEndpointURL: https://my346188.crm.ondemand.comsap/byd/odata/v1/c4codataapi
        secretName: app-c4c-my346188-70702698-4671-4a6c-a52d-d7609c7fe0e5
        type: Basic
      gatewayUrl: http://app-c4c-my346188-70702698-4671-4a6c-a52d-d7609c7fe0e5.kyma-integration.svc.cluster.local
      specificationUrl: https://XXXX:XXXX@my346188.crm.ondemand.com/sap/byd/odata/v1/c4codataapi/$metadata
      targetUrl: https://my346188.crm.ondemand.com
```
